### ISSUE TITLE
Creating registration form: Unexpected token =

### ISSUE THREAD

**Issue by kingoftheconnors** [matrix-org/matrix-appservice-slack#128]
I'm new to Synapse, so please bear with me.

I have set up a Matrix server on Digital Ocean. It runs from a Ubuntu droplet. On this same droplet I want to run this bridge to Slack. I installed npm and nodejs and tried to create the registration form with `nodejs app.js -r -c config.yaml -u "http://DROPLET_IP_ADDRESS:445"` and got this error:
```
SyntaxError: Unexpected token =
                     at exports.runInThisContext (vm.js:53:16)
                     at Module._compile (module.js:374:25)
                     at Object.Module._extensions..js (module.js:417:10)
                     at Module.load (module.js:344:32)
                     at Function.Module._load (module.js:301:12)
                     at Module.require (module.js:354:17)
                     at require (internal/module.js:12:17)
                     at Object.<anonymous> (/root/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/exports.js:4:25)
                      at Module._compile (module.js:410:26)
                      at Object.Module._extensions..js (module.js:417:10)
```

I tried installing nodejs-legacy and got the same result. What should I do?

**Comment by kingoftheconnors** [comment]
So, Digital Ocean sets up a super-old version of node with its Ubuntu droplets. For anyone else with this problem, you have to update the `dev` using `curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh` and `sudo bash nodesource_setup.sh`. Then you can uninstall and reinstall nodejs.
