### ISSUE TITLE
Edits generates errors on log M>S

### ISSUE THREAD

**Issue by olmari** [matrix-org/matrix-appservice-slack#180]
While edits from S>M seems to work just fine, M>S does generate odd stuff in debug log, edits themselves still seems to work. Below is bridge debug log from initial message and then attempted edit:

```
Aug 11 23:54:47 matrix node[30329]: Aug-11 23:54:47.722 DEBUG SlackEventHandler Received slack event: { token: '<REDACTED> ',
Aug 11 23:54:47 matrix node[30329]:   team_id: 'T4VQB4VAM',
Aug 11 23:54:47 matrix node[30329]:   api_app_id: 'AKDQS4K52',
Aug 11 23:54:47 matrix node[30329]:   event:
Aug 11 23:54:47 matrix node[30329]:    { type: 'message',
Aug 11 23:54:47 matrix node[30329]:      subtype: 'bot_message',
Aug 11 23:54:47 matrix node[30329]:      text: 'jee, toimii ainaki tännepäin',
Aug 11 23:54:47 matrix node[30329]:      ts: '1565556887.091600',
Aug 11 23:54:47 matrix node[30329]:      username: 'Sami Olmari',
Aug 11 23:54:47 matrix node[30329]:      icons:
Aug 11 23:54:47 matrix node[30329]:       { image_48: 'https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2019-06-11/662085067904_48.png' },
Aug 11 23:54:47 matrix node[30329]:      bot_id: 'BKEA52BFF',
Aug 11 23:54:47 matrix node[30329]:      channel: 'C5KBB4Y67',
Aug 11 23:54:47 matrix node[30329]:      event_ts: '1565556887.091600',
Aug 11 23:54:47 matrix node[30329]:      channel_type: 'channel' },
Aug 11 23:54:47 matrix node[30329]:   type: 'event_callback',
Aug 11 23:54:47 matrix node[30329]:   event_id: 'EvM8HTQUTW',
Aug 11 23:54:47 matrix node[30329]:   event_time: 1565556887,
Aug 11 23:54:47 matrix node[30329]:   authed_users: [ 'UK7V9T22V' ] }
Aug 11 23:55:41 matrix node[30329]: Aug-11 23:55:41.774 INFO bridge ::ffff:127.0.0.1 - - [11/Aug/2019:20:55:41 +0000] "PUT /transactions/7741?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.2.1"
Aug 11 23:55:41 matrix node[30329]: Aug-11 23:55:41.778 INFO Main edit in progress
Aug 11 23:55:41 matrix node[30329]: Aug-11 23:55:41.779 DEBUG substitutions Event from matrix: {"age":209,"content":{"body":"jee, toimii ainaki tännepäin - edit ehkä sinnekkinpäin tässä","msgtype":"m.text"},"event_id":"$15655569411501aTrTA:hacklab.fi","origin_server_ts":1565556941510,"room_id":"!pEWpdIBwrVmKlmizMx:matrix.org","sender":"@olmari:hacklab.fi","type":"m.room.message","unsigned":{"age":209},"user_id":"@olmari:hacklab.fi"}
Aug 11 23:55:41 matrix node[30329]: Aug-11 23:55:41.779 INFO bridge [-] GET http://localhost:8008/_matrix/client/r0/rooms/!pEWpdIBwrVmKlmizMx%3Amatrix.org/state (AS) Body:
Aug 11 23:55:41 matrix node[30329]: Aug-11 23:55:41.893 INFO bridge [-] GET http://localhost:8008/_matrix/client/r0/rooms/!pEWpdIBwrVmKlmizMx%3Amatrix.org/state (AS) HTTP 200 "[{\"origin_server_ts\": 1526185886680, \"sender\": \"@freenode_Demus_:matrix.or
Aug 11 23:55:42 matrix node[30329]: Aug-11 23:55:42.833 DEBUG SlackEventHandler Received slack event: { token: '<REDACTED> ',
Aug 11 23:55:42 matrix node[30329]:   team_id: 'T4VQB4VAM',
Aug 11 23:55:42 matrix node[30329]:   api_app_id: 'AKDQS4K52',
Aug 11 23:55:42 matrix node[30329]:   event:
Aug 11 23:55:42 matrix node[30329]:    { type: 'message',
Aug 11 23:55:42 matrix node[30329]:      subtype: 'message_changed',
Aug 11 23:55:42 matrix node[30329]:      hidden: true,
Aug 11 23:55:42 matrix node[30329]:      message:
Aug 11 23:55:42 matrix node[30329]:       { type: 'message',
Aug 11 23:55:42 matrix node[30329]:         subtype: 'bot_message',
Aug 11 23:55:42 matrix node[30329]:         text: 'jee, toimii ainaki tännepäin - edit ehkä sinnekkinpäin tässä',
Aug 11 23:55:42 matrix node[30329]:         username: 'Sami Olmari',
Aug 11 23:55:42 matrix node[30329]:         icons: [Object],
Aug 11 23:55:42 matrix node[30329]:         bot_id: 'BKEA52BFF',
Aug 11 23:55:42 matrix node[30329]:         ts: '1565556887.091600',
Aug 11 23:55:42 matrix node[30329]:         user_team: 'T4VQB4VAM',
Aug 11 23:55:42 matrix node[30329]:         source_team: 'T4VQB4VAM' },
Aug 11 23:55:42 matrix node[30329]:      channel: 'C5KBB4Y67',
Aug 11 23:55:42 matrix node[30329]:      previous_message:
Aug 11 23:55:42 matrix node[30329]:       { type: 'message',
Aug 11 23:55:42 matrix node[30329]:         subtype: 'bot_message',
Aug 11 23:55:42 matrix node[30329]:         text: 'jee, toimii ainaki tännepäin',
Aug 11 23:55:42 matrix node[30329]:         ts: '1565556887.091600',
Aug 11 23:55:42 matrix node[30329]:         username: 'Sami Olmari',
Aug 11 23:55:42 matrix node[30329]:         icons: [Object],
Aug 11 23:55:42 matrix node[30329]:         bot_id: 'BKEA52BFF' },
Aug 11 23:55:42 matrix node[30329]:      event_ts: '1565556941.091700',
Aug 11 23:55:42 matrix node[30329]:      ts: '1565556941.091700',
Aug 11 23:55:42 matrix node[30329]:      channel_type: 'channel' },
Aug 11 23:55:42 matrix node[30329]:   type: 'event_callback',
Aug 11 23:55:42 matrix node[30329]:   event_id: 'EvM927QZJ9',
Aug 11 23:55:42 matrix node[30329]:   event_time: 1565556941,
Aug 11 23:55:42 matrix node[30329]:   authed_users: [ 'UK7V9T22V' ] }
Aug 11 23:55:42 matrix node[30329]: Aug-11 23:55:42.840 ERROR BridgedRoom Failed to process event
Aug 11 23:55:42 matrix node[30329]: Aug-11 23:55:42.841 ERROR BridgedRoom TypeError: Cannot read property 'update' of undefined
Aug 11 23:55:42 matrix node[30329]:     at BridgedRoom.onSlackMessage (/opt/matrix-slack/matrix-appservice-slack/lib/BridgedRoom.js:446:21)
Aug 11 23:55:42 matrix node[30329]:     at <anonymous>
Aug 11 23:55:42 matrix node[30329]:     at process._tickCallback (internal/process/next_tick.js:188:7)
```

Bridge version 48a5a7b9b6e5151ee539e2122f9770b2e173ace6

**Comment by Cadair** [comment]
That looks like it has failed to lookup the event in the store and that it isn't being caught properly.

**Comment by Half-Shot** [comment]
I think this is now fixed.
