### ISSUE TITLE
Unclear doc for config

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-appservice-slack#304]
I'm trying to set up the bridge on my a-dozen-people-homeserver using docker. The whole docker installation process is only so-so documented for docker-noobs to begin with. The issue I'm facing is generally that it's unclear what services are included in the container (e.g. postgresql? Seems not: ECONNREFUSED) and what means what. What features exactly are covered anyway and what of the optional settings do I need to set up? What will the OAuth allow me to do? Add channels on matrix or slack?

So I decided on nedb as it seems to be less of a hassle because: Where is postgresql? How to set it up?

I'm specifically facing this following resulting issue.

conf.yaml:
```
  engine: "nedb" # "postgres" or "nedb". If using "nedb", do not define connectionString
```
so I comment out the next line `connectionString`.

alas:
```
$ docker run -v ~synapse/bridges/slack/:/config/ matrixdotorg/matrix-appservice-slack

{"field":"data.db.connectionString","message":"is required","value":{"engine":"nedb"},"type":"object","schemaPath":["properties","db"]}
The field data.db.connectionString is [object Object] which is required
/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:44
        throw e;
        ^

Error: Failed to validate file
    at ConfigValidator.validate (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:42:17)
    at Cli._loadConfig (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:160:22)
    at Cli._assignConfigFile (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:145:23)
    at Cli.run (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cli.js:139:10)
    at Object.<anonymous> (/usr/src/app/lib/app.js:46:5)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  _validationErrors: [
    {
      field: 'data.db.connectionString',
      message: 'is required',
      value: [Object],
      type: 'object',
      schemaPath: [Array]
    }
  ]
}
```

Okay, lets try `connectionString: ""`.

Nope:
```
$ docker run -v ~synapse/bridges/slack/:/config/ matrixdotorg/matrix-appservice-slack

Oct-21 23:22:00.096 INFO Main Enabled RTM
Oct-21 23:22:00.183 INFO Main Loading databases
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [DailyRotateFile]. Use emitter.setMaxListeners() to increase limit
(node:1) DeprecationWarning: prom-client - Passing a non-object to metrics constructor is deprecated
Oct-21 23:22:00.208 INFO Main Loading teams.db
Oct-21 23:22:00.454 INFO SlackHookHandler Slack-side listening on port 9898 over https
Oct-21 23:22:00.480 INFO bridge [-] GET http://localhost:8008/_matrix/client/r0/joined_rooms (AS) Body:
Oct-21 23:22:00.496 INFO Main Fetching teams
Oct-21 23:22:00.537 INFO Main Loaded 0 teams
Oct-21 23:22:00.542 INFO Main Finished loading all team clients
Oct-21 23:22:00.546 ERROR app Failed to start: TypeError: Cannot read property 'select' of undefined
    at NedbDatastore.getAllRooms (/usr/src/app/lib/datastore/NedbDatastore.js:53:38)
    at Main.run (/usr/src/app/lib/Main.js:672:46)
```

**Comment by HarHarLinks** [comment]
This might be wrong:

https://github.com/matrix-org/matrix-appservice-slack/blob/ba7bc17fc55d6b3223cf499c299e17a92e375e19/config/slack-config-schema.yaml#L39

**Comment by Half-Shot** [comment]
>So I decided on nedb as it seems to be less of a hassle because: Where is postgresql? How to set it up?
https://github.com/matrix-org/matrix-appservice-slack/blob/master/docs/datastores.md

**Comment by HarHarLinks** [comment]
I don't know how I overlooked the link to datastores.md. However maybe the requirements should also list psql.

I think at least the doc for the docker variant should include the problems you face due to network bridging (allow the interface for psql access, firewalls, docker IPs) and could also be clearer on what ports are used by what service, need to be public facing, what the defaults are. The defaults introduce 9898 as an explicit default (on the homeserver) and implicitly 5858 on the bridge, where 9898 could be mistaken as default `$MATRIX_PORT`.

**Comment by Half-Shot** [comment]
I thought we were more explicit about datastores.md, but perhaps we are not. If you try to use NeDB it will warn you and link you though in the logs. Because setting up postgres can vary from system to system, we've avoided stating explicitly default ports or configurations for that as we might mislead -- it's better to refer to the official docs than ask us.

9898 is for slack webhooks / events api stuff - which is why it's called `slack_hook_port` in the config.

5858 is for the bridge to listen in for incoming messages - which is also documented in the same config as appservice_port. Sadly, we decided to use a different number but hey ho.

**Comment by HarHarLinks** [comment]
I'm gonna create a PR [as suggested](https://matrix.to/#/!vCpZvJFNjuiBkDAvEs:cadair.com/$Nfi-lEqlzld-ULaxzGUskyZSwzFEOhrnJIa6IjAu-3Q?via=half-shot.uk&via=matrix.org&via=sorunome.de) with some small details missing from the doc, but I think for actual good instructions a complete rewrite will be needed.

Here's some more thoughts on docker networking config:
- either use `--network=host`
- or for better compartmentalization stay with bridged networking mode but some additional config is required:
  - forward the ports: `-p 5858:5858 -p 9898:9898` for public facing ports + allowing synapse to route to docker by `localhost:5858`.
  - make postgresql listen on `172.17.0.1/16` via postgresql.conf + pg_hba.conf
  - don't forget to open firewall (9898 in from public, both out to docker(?), $postgresql_port in from docker). Please advice does `5858` need to be public?

What i'm totally missing is how to set up oauth (slack? homeserver?) and what features this brings. What puppet? If these are general concepts, link to the general doc/spec.

>if you want to bridge files, the OAuth Access Token
???

The help command won't show any help for oauth and neither for "bridge files". Also only the old linking method is explained there, I think.

**Comment by HarHarLinks** [comment]
I have since learned more about docker. If this is to be taken as a serious installation method, a compose.yaml file that works with both `docker stack` and `docker-compose` should be provided.

**Comment by PavlosMelissinos** [comment]
Any update here?

@HarHarLinks If you have a working `docker-compose.yaml` I'd love to take a look

**Comment by HarHarLinks** [comment]
@PavlosMelissinos I have not used the bridge since and no `docker-compose.yaml`. I don't remember much at this point, so all I can tell you is what you'll find in the PR. Keep in mind things may have changed in the last 14 months such that this may or may not apply as I left it anymore. I'm happy you're willing to pick this up and potentially make it a one click setup :)
