### ISSUE TITLE
Service crashes and docker restarts on link command

### ISSUE THREAD

**Issue by nscaife** [matrix-org/matrix-appservice-slack#345]
I'm running a Matrix homeserver using the [Ansible playbook](https://github.com/spantaleev/matrix-docker-ansible-deploy). Everything seems to be working fine until I issue the link command, which causes the appservice to immediately crash and the Docker container it's in to restart.  The slackbot user in Matrix never replies to the command. Here is the output from attaching to the Docker instance when it crashes:

```Jan-17 04:34:01.605 INFO bridge ::ffff:172.18.0.8 - - [17/Jan/2020:04:34:01 +0000] "PUT /transactions/68?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.8.0"

Jan-17 04:34:01.607 INFO Main Admin: link --channel_id X --room X --slack_bot_token X --webhook_url X

/usr/src/app/lib/datastore/NedbDatastore.js:119
                delete doc._id;
                ^

TypeError: Cannot convert undefined or null to object
    at /usr/src/app/lib/datastore/NedbDatastore.js:119:17
    at newArguments.<computed> (/usr/src/app/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/usr/src/app/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/usr/src/app/node_modules/nedb/lib/cursor.js:126:19)
    at /usr/src/app/node_modules/nedb/lib/cursor.js:193:12
    at /usr/src/app/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/usr/src/app/node_modules/async/lib/async.js:130:20)
    at /usr/src/app/node_modules/nedb/lib/datastore.js:323:11
    at fn (/usr/src/app/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/src/app/node_modules/async/lib/async.js:498:34)
    at processImmediate (internal/timers.js:439:21)```

**Comment by jaller94** [comment]
We want to drop support for NeDB. Please migrate to PostgreSQL. This bridge offers a database migrator.

#224
