### ISSUE TITLE
New Slack Apps do not support as_user or RTM

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-slack#348]
We need to add documentation to explain to users how to create "Classic" Slack apps. We also need to support New Slack apps.

**Comment by Cadair** [comment]
:sob:

**Comment by Cadair** [comment]
Given:

> New apps currently cannot override their username or icon when posting messages. That ability will arrive soon, and your app can request a new scope to enable it.

From https://api.slack.com/authentication/quickstart#soon I would propose we explicitly do not support "new" slack apps until that feature lands. RTM is obviously a shame, but we still have the events code which people can use if they want to use a new app for some reason.

**Comment by ErrorProne** [comment]
Hi there, I guess an explanation would be helpful. We currently run into

`Feb-6 13:50:32.171 ERROR Main Failed processing matrix message:  { Error: An API error occurred: invalid_arguments
    at Object.platformErrorFromResult (/opt/matrix-appservice-slack/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/opt/matrix-appservice-slack/node_modules/@slack/web-api/dist/WebClient.js:465:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'slack_webapi_platform_error',
  data: 
   { ok: false,
     error: 'invalid_arguments',
     deprecated_argument: 'as_user',
     response_metadata: { scopes: [Array], acceptedScopes: [Array] } } }
`

Which totally sounds like it could be because of the changes made by slack.
Do you guys have any pointers how to create a "classic" slack app?

**Comment by Cadair** [comment]
You can follow this link: https://api.slack.com/apps?new_classic_app=1

**Comment by ErrorProne** [comment]
Quickest response ever!
Thank you, I'll try that out =)

**Comment by Sorunome** [comment]
And under "App Home" you have to add a legacy bot user

**Comment by Half-Shot** [comment]
#356 adds a note to the README, but we still need to fix this.

**Comment by Cadair** [comment]
They do now have support for name and avatar though: https://api.slack.com/scopes/chat:write.customize (that's @tulir )

**Comment by Half-Shot** [comment]
Ah awesome. Easy to fix then.

**Comment by edwardando** [comment]
Hi all, I'm coming from https://github.com/spantaleev/matrix-docker-ansible-deploy
I have a similar issue to above:

`
INFO 19:49:47:708 [Main] Handling matrix room message $xnW9iFriI_Grh0pQh14Kcp3MA82YGrtK4_Oz62xBHBU !CkEPfvaZTSDYIqltEX:domain.me
DEBUG 19:49:47:766 [slack-api] apiCall('chat.postMessage') start
DEBUG 19:49:47:768 [slack-api] will perform http request
DEBUG 19:49:47:922 [slack-api] http response received
ERROR 19:49:47:923 [Main] Failed processing matrix message:  Error: An API error occurred: invalid_arguments
    at platformErrorFromResult (/usr/src/app/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/usr/src/app/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BridgedRoom.onMatrixMessage (/usr/src/app/lib/BridgedRoom.js:459:19)
    at async Main.onMatrixEvent (/usr/src/app/lib/Main.js:749:23) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_arguments',
    deprecated_argument: 'as_user',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
`

But I'm 100% sure that I have made a classic app. I've tried with both granular and regular scopes.
Any thought what might cause this?
