### ISSUE TITLE
Slack Puppeting

### ISSUE THREAD

**Issue by ErrorProne** [matrix-org/matrix-appservice-slack#361]
I believe I overlooked something or it is simply a documentation issue. When trying 1:1 DM I always get: "You have not enabled puppeting for this Slack workspace. You must do that to speak to members."
Google gave me no, to me, meaningful results for puppeting and slack. I've greped through the code to find some hints where to enable what but I guess I know too little about slack.

Maybe you guys can give me any pointers? I would be happy to update the doc =)

**Comment by charvp** [comment]
You need to send a message in the control room containing `oauth <your matrix id> true`. That's what made that work for me, at least.

**Comment by ErrorProne** [comment]
Oh great, thanks! We havn't set up the oauth at all. Sadly I've only access to the matrix part, but maybe the slack owner can figure the slack part out and hopefully we'll get some useful information out of this.

**Comment by kupiqu** [comment]
> You need to send a message in the control room containing `oauth <your matrix id> true`. That's what made that work for me, at least.

Can you elaborate a little? I'm trying to do this but it doesn't seem to work. I must be doing sth wrong. By control room you mean the room that displayed the error "You have not enabled puppeting for this Slack workspace. You must do that to speak to members.", or somewhere else?

**Comment by tomaskrizek** [comment]
To enable puppetting and 1-1 conversations:
- In the Matrix channel that has Slack integration, view a list of users
- Start a direct message chat with `Slack Integration` user
- Send message: `login`
- Click the link and authorize the app on Slack

**Comment by kupiqu** [comment]
> * login

It worked great, thank you very much!

**Comment by hlesueur** [comment]
@charvp  
> 
> You need to send a message in the control room containing `oauth <your matrix id> true`. That's what made that work for me, at least.

Where would you type such thing? 
Thanks for your help (the login on the slack integration bot fails for me)

**Comment by charvp** [comment]
> Where would you type such thing?
> Thanks for your help (the login on the slack integration bot fails for me)

The message I posted is for self-hosted bridges.

**Comment by kupiqu** [comment]
> To enable puppetting and 1-1 conversations:
> 
> * In the Matrix channel that has Slack integration, view a list of users
> * Start a direct message chat with `Slack Integration` user
> * Send message: `login`
> * Click the link and authorize the app on Slack

I did this ↑ in riot-desktop 1.6.0.1 and it worked for me

**Comment by hlesueur** [comment]
yep.. for me it says 
![image](https://user-images.githubusercontent.com/62343457/81719743-bc591900-947d-11ea-8feb-e17e5142fd26.png)

**Comment by kupiqu** [comment]
> yep.. for me it says
> ![image](https://user-images.githubusercontent.com/62343457/81719743-bc591900-947d-11ea-8feb-e17e5142fd26.png)
> 
> (while it worked for other slack workspaces, it doesn't for the one I'm trying to link now)

Are you sure Riot as an app is enabled in that Slack workspace?

**Comment by hlesueur** [comment]
yes, it's installed. The bridge is working more or less. But when I try to link my own bot it fails.

**Comment by kupiqu** [comment]
> yes, it's installed. The bridge is working more or less. But when I try to link my own bot it fails.

sorry, no idea. only thing I'd try is revoking the Riot app, and starting over

**Comment by hlesueur** [comment]
I did that already...
Now it's all broken !! It no longer works... even the main bridge which was working

**Comment by kupiqu** [comment]
> Now it's all broken !! It no longer works... even the main bridge which was working

Sorry to hear that. Unfortunately, it seems you have a new and bigger problem to fix before trying the puppeting thing again...

If my last advise wouldn't have resolved so badly, I'd suggest searching about Riot bridge reinstall problems in Slack and if you don't find anything meaningful then opening a new bug for that.

If you end up doing the latter, I'd also suggest being a bit more specific, "all broken and not working" can happen in many ways or mean different things. 

One last (more speculative) comment, it may be that you need to restart the communication bridge with that slack workspace in Riot as well, but after the success of my previous suggestion, let me remind you that you decide or not to make these steps at your own risk. I am trying to help but there are no guarantees that this will work or worsen things even further.

**Comment by hlesueur** [comment]
thank you for your answer. 
Don't worry, I had done the step you suggested before you wrote your message :-) 

Please, can you specify what you mean by "restart the communication bridge" ? 
When I removed permissions for the Riot_bridge app in slack, I put them back by starting over slack integration in RIOT. 
Is that what you meant, or is there another step I'm not aware?

**Comment by kupiqu** [comment]
That is what I meant, yes. However, given that you removed Riot_bridge app in slack, when you try this out in Riot, it should open the browser again like it did the first time, so slack accepts Riot_bridge as an app, just as before the removal.

Not sure this is what's happening, but it could be that this step is not done because Riot thinks Slack is on the other side, but actually it is not because you removed it. If so, I guess you will need to remove the slack workspace bridge in Riot too, and restart the communication from Riot.

It's likely you did this already, in which case I'm out of ideas :/

**Comment by hlesueur** [comment]
I think I understood the problem:
upon removing and re-creating the app in slack, its presence goes to 'away'
So the app no longer relays messages from slack

**Comment by freelock** [comment]
I am successfully puppeted on one Slack team, originally done using the oauth command in the main command room. However, I'm getting the error messages noted above when I attempt to use a DM with the slack bridge to log into other Slack teams. 

Is that what this issue is about -- puppeting on more than one team? If not, I'll file a new bug...

**Comment by hlesueur** [comment]
Hello @freelock I'm successfully puppeted to two slack teams, but unsuccessfully to a third
Unclear...

**Comment by freelock** [comment]
I just switched my bridge over from the "slack-v14-fix" Docker tag to the "stable" tag, and tried using the "login" direct message to my Slack user. This got me an authorization link, which let me pick a slack team to authorize. However, when I attempted to authorize, I got a page that says:

Integration Failed
Unfortunately, your account did not go as expected...

... and the bridge logged this message:

```
Jun-14 16:38:34.375 INFO Main Handled $<event> (!<roomid>:matrix.freelock.com)
Jun-14 16:39:13.083 INFO SlackHookHandler Received slack webhook GET /<token>/authorize?code=<token>: {}
Jun-14 16:39:13.434 ERROR SlackHookHandler Error during handling of an oauth token: error: duplicate key value violates unique constraint "puppets_matrixuser_key"
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:581:48)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:116:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 231,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (matrixuser)=(@john:matrix.freelock.com) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'puppets',
  column: undefined,
  dataType: undefined,
  constraint: 'puppets_matrixuser_key',
  file: 'nbtinsert.c',
  line: '432',
  routine: '_bt_check_unique'
}
```
... so this looks to me that there's still a schema-level problem with allowing a user to puppet on multiple teams...

**Comment by auscompgeek** [comment]
@freelock The schema was fixed in 1.4.0-rc1.

**Comment by williamkray** [comment]
what does it mean if i'm able to do all the setup for this, and running either the `login` or `oauth` commands always takes me to a functional slack page asking for authorization, but any endpoint they redirect to back on my appservice server throws a 404? I've quadruple-checked to make sure my redirect uri matches the endpoint the app is supposed to hit, but literally nothing i configure has a functional endpoint, despite the service actively listening.
