### ISSUE TITLE
Uncaught promise: Call to synapse/…/avatar_url

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-slack#453]
I'm not sure how to make them reproducible, but I get these uncaught errors when starting up my appservice.
```
Jul-27 19:48:50.319 INFO bridge [-] PUT http://localhost:8008/_matrix/client/r0/profile/%40slack_matrix-bridge-dev_U013XFQ43EU%3Asynapse-dev.local/avatar_url (@slack_matrix-bridge-dev_U013XFQ43EU:synapse-dev.local) Body: "{}"
Jul-27 19:48:50.325 ERROR bridge [-] PUT http://localhost:8008/_matrix/client/r0/profile/%40slack_matrix-bridge-dev_U013XFQ43EU%3Asynapse-dev.local/avatar_url (@slack_matrix-bridge-dev_U013XFQ43EU:synapse-dev.local) HTTP 400 Error: "{\"errcode\":\"M_MISSING_PARAM\",\"error\":\"Missing key 'avatar_url'\"}"
(node:290394) UnhandledPromiseRejectionWarning: M_MISSING_PARAM: Missing key 'avatar_url'
    at parseErrorResponse (/home/jaller94/Git/matrix-appservice-slack/node_modules/matrix-js-sdk/lib/http-api.js:849:13)
    at /home/jaller94/Git/matrix-appservice-slack/node_modules/matrix-js-sdk/lib/http-api.js:804:17
    at /home/jaller94/Git/matrix-appservice-slack/node_modules/matrix-js-sdk/lib/http-api.js:738:9
    at Request._callback (/home/jaller94/Git/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:78:13)
    at Request.self.callback (/home/jaller94/Git/matrix-appservice-slack/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/home/jaller94/Git/matrix-appservice-slack/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/home/jaller94/Git/matrix-appservice-slack/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:290394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

**Comment by williamkray** [comment]
i also get those, i didn't realize it was associated with the avatar calls and thought it might be related to my inability to make puppeting work.

i can supply logs as well if you want to cross-reference.

**Comment by jaller94** [comment]
Thanks, but I also fixed it locally. Will be pushing a PR soonish and give it to review.
