### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by almereyda** [matrix-org/matrix-appservice-slack#47]
When running the cli in a Docker container, an error is thrown:

```
slack-appservice_1  | TypeError: Cannot read property 'url' of undefined
slack-appservice_1  |     at Function.AppServiceRegistration.fromObject (/usr/src/app/node_modules/matrix-
appservice/lib/app-service-registration.js:231:13)
slack-appservice_1  |     at Cli._startWithConfig (/usr/src/app/node_modules/matrix-appservice-bridge/lib/
components/cli.js:182:32)
slack-appservice_1  |     at Cli.run (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/cl
i.js:139:10)
slack-appservice_1  |     at Object.<anonymous> (/usr/src/app/app.js:28:5)
slack-appservice_1  |     at Module._compile (module.js:570:32)
slack-appservice_1  |     at Object.Module._extensions..js (module.js:579:10)
slack-appservice_1  |     at Module.load (module.js:487:32)
slack-appservice_1  |     at tryModuleLoad (module.js:446:12)
slack-appservice_1  |     at Function.Module._load (module.js:438:3)
slack-appservice_1  |     at Module.runMain (module.js:604:10)
slack-appservice_1  |     at run (bootstrap_node.js:389:7)
slack-appservice_1  |     at startup (bootstrap_node.js:149:9)
slack-appservice_1  |     at bootstrap_node.js:504:3
```

The example.sample.yaml does not contain the required field: https://github.com/matrix-org/matrix-appservice-slack/blob/master/config/config.sample.yaml

Unfortunately it is required from https://github.com/matrix-org/matrix-appservice-node/blob/master/lib/app-service-registration.js#L231

What am I missing here?

**Comment by Half-Shot** [comment]
It looks like the URL was just not defined or your config didn't make it's way intact onto docker? Please reopen if I'm missing something.
