### ISSUE TITLE
M->S: Some reactions are not supported

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-slack#503]
**Describe the bug**
Some reactions are not supported by Slack and silently fail to bridge.

**To Reproduce**
1. On matrix make a post and react to it using 🧙.

**Expected behavior**
This gets somehow bridged to Slack.

**Screenshots**
### Matrix
![Screenshot_2020-09-23_18-22-00](https://user-images.githubusercontent.com/10872136/94040907-ce52ad00-fdc9-11ea-9419-7a019780e8f1.png)

### Slack
![Screenshot_2020-09-23_18-22-09](https://user-images.githubusercontent.com/10872136/94040871-c135be00-fdc9-11ea-9e8e-f37384f69e9e.png)

**Additional context**
```
Sep-23 17:36:50.301 ERROR Main Failed processing reaction message:  Error: An API error occurred: invalid_name
    at Object.platformErrorFromResult (/home/jaller94/Git/matrix-appservice-slack/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/home/jaller94/Git/matrix-appservice-slack/node_modules/@slack/web-api/dist/WebClient.js:152:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async BridgedRoom.onMatrixReaction (/home/jaller94/Git/matrix-appservice-slack/lib/BridgedRoom.js:246:21)
    at async Main.onMatrixEvent (/home/jaller94/Git/matrix-appservice-slack/lib/Main.js:531:17) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_name',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

**Comment by Half-Shot** [comment]
I wonder what the name is. `:mage:` is valid on slack

**Comment by Half-Shot** [comment]
So trying this on Slack, they only offer female_mage and male_mage as actual names. Clicking :mage: on slack will give you female mage.

**Comment by jaller94** [comment]
`node-emoji` wasn't able to translate it an send the Unicode 🧙

**Comment by Half-Shot** [comment]
Well, the best thing we can do is either ignore invalid reactions, or send a reply to the message showing the reaction.

**Comment by jaller94** [comment]
Not to distract from the "There are some unsupported strings that we should better represent in Slack", but just to clarify why mage doesn't work:

The library `node-emoji` does not translate 🧙 to `:mage:` because Slack doesn't have gender-neutral reactions.
Instead, looking at the inverse mapping (S->M), both `:mage:` and `:female_mage:` translate to 🧙‍♀ (female mage).
https://github.com/omnidan/node-emoji/blob/master/lib/emoji.json
