### ISSUE TITLE
ERROR BridgedRoom Error storing activity metrics error: date/time field value out of range: "2021-0-4"

### ISSUE THREAD

**Issue by olmari** [matrix-org/matrix-appservice-slack#552]
**Describe the bug**

Happends on latest master (which correlates to 1.6.1 at the moment) and latest develop branch. Sending any messages M>S does not work, instead we get this error on bridge log:

```
tammi 04 12:58:18 morpheus node[2431]: Jan-4 12:58:18.672 INFO Main Handling matrix room message $b2JwwtwZ4ueUORQtcBwk5He_BJBmHfXNfvK4ayC7UG4 !OwkWEsdHkzXRAQkApj:hacklab.fi
tammi 04 12:58:18 morpheus node[2431]: Jan-4 12:58:18.998 ERROR BridgedRoom Error storing activity metrics error: date/time field value out of range: "2021-0-4"
tammi 04 12:58:18 morpheus node[2431]:     at Parser.parseErrorMessage (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:278:15)
tammi 04 12:58:18 morpheus node[2431]:     at Parser.handlePacket (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:126:29)
tammi 04 12:58:18 morpheus node[2431]:     at Parser.parse (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/parser.js:39:38)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.<anonymous> (/opt/slackbot/matrix-appservice-slack/node_modules/pg-protocol/dist/index.js:8:42)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.emit (events.js:314:20)
tammi 04 12:58:18 morpheus node[2431]:     at addChunk (_stream_readable.js:297:12)
tammi 04 12:58:18 morpheus node[2431]:     at readableAddChunk (_stream_readable.js:272:9)
tammi 04 12:58:18 morpheus node[2431]:     at Socket.Readable.push (_stream_readable.js:213:10)
tammi 04 12:58:18 morpheus node[2431]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
tammi 04 12:58:18 morpheus node[2431]:   length: 168,
tammi 04 12:58:18 morpheus node[2431]:   severity: 'ERROR',
tammi 04 12:58:18 morpheus node[2431]:   code: '22008',
tammi 04 12:58:18 morpheus node[2431]:   detail: undefined,
tammi 04 12:58:18 morpheus node[2431]:   hint: 'Perhaps you need a different "datestyle" setting.',
tammi 04 12:58:18 morpheus node[2431]:   position: '128',
tammi 04 12:58:18 morpheus node[2431]:   internalPosition: undefined,
tammi 04 12:58:18 morpheus node[2431]:   internalQuery: undefined,
tammi 04 12:58:18 morpheus node[2431]:   where: undefined,
tammi 04 12:58:18 morpheus node[2431]:   schema: undefined,
tammi 04 12:58:18 morpheus node[2431]:   table: undefined,
tammi 04 12:58:18 morpheus node[2431]:   column: undefined,
tammi 04 12:58:18 morpheus node[2431]:   dataType: undefined,
tammi 04 12:58:18 morpheus node[2431]:   constraint: undefined,
tammi 04 12:58:18 morpheus node[2431]:   file: 'datetime.c',
tammi 04 12:58:18 morpheus node[2431]:   line: '3739',
tammi 04 12:58:18 morpheus node[2431]:   routine: 'DateTimeParseError'
tammi 04 12:58:18 morpheus node[2431]: }
tammi 04 12:58:19 morpheus node[2431]: Jan-4 12:58:19.003 INFO Main Handled $b2JwwtwZ4ueUORQtcBwk5He_BJBmHfXNfvK4ayC7UG4 (!OwkWEsdHkzXRAQkApj:hacklab.fi)
```

**To Reproduce**
1. Live in 2021 (Not entirely sure when this started, but 2021 is strong candidate)
2. See error

**Expected behavior**
Messages to work normally

Server:
Debian buster
Postgresql 13
Synapse 1.24.0

**Comment by olmari** [comment]
Also we have `enable_metrics: false` so if rootissue is somewhere in metrics it shouldn't indeed fail to that at all, should sending message to fail anyway regardless of metrics issues and it enabled or not :)

**Comment by olmari** [comment]
Saw similar in: `Dec-31 23:57:29.081 error BridgedRoom Error storing activity metrics error: date/time field value out of range: "2020-11-31"` which is obviously also false as nove,ber has 30 days, but thing is that log is from december 31st... So some rootissue is that for any reason month calculation starts at 0, should be 1.

**Comment by jaller94** [comment]
Found the bug.
The month has always been off by one.
`date.getMonth()` is zero-based (meaning January = 0) but it must be incremented by one to be a valid date.

**Comment by olmari** [comment]
I confirm above PR working. Or no errors on logs and messaging both ways works, so I'd say fixe, thank you! :)
