### ISSUE TITLE
Team channels sync fails with Invalid characters in room alias

### ISSUE THREAD

**Issue by rissson** [matrix-org/matrix-appservice-slack#603]
**Describe the bug**

Team channel sync fails because of invalid characters in the room alias. I suspect this is because of the leading `#`.

**To Reproduce**
1. Configure team synchronisation:
```
team_sync:
  TEAMID:
    channels:
      enabled: true
      allow_private: true
      allow_public: true
      alias_prefix: "MYTEAM "
    users:
      enabled: true
```
2. Restart the service
3. See error

**Expected behavior**

Team is getting synced and I get a notification in the control channel that channels have been created.

**Screenshots**

Here are the logs:

```
May-22 22:43:23.689 INFO bridge [-] POST http://synapse.matrix.svc.cluster.local:80/_matrix/client/r0/createRoom (@slack_some-team_CHANNEL_ID:lama-corp.space) Body: "{\"name\":\"#music\",\"topic\":\"\",\"visibility\":\"public\",\"room_alias
_name                                                      
May-22 22:43:23.695 ERROR bridge [-] POST http://synapse.matrix.svc.cluster.local:80/_matrix/client/r0/createRoom (@slack_some-team_CHANNEL_ID:lama-corp.space) HTTP 400 Error: "{\"errcode\":\"M_UNKNOWN\",\"error\":\"Invalid characters in ro
om alias\"}"                                               
May-22 22:43:23.696 ERROR TeamSyncer Failed to provision new room dynamically: M_UNKNOWN: Invalid characters in room alias
    at parseErrorResponse (/usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:827:13)
    at /usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:782:17
    at /usr/src/app/node_modules/matrix-js-sdk/lib/http-api.js:716:9
    at Request._callback (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:79:17)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28) {
  errcode: 'M_UNKNOWN',                                    
  data: { errcode: 'M_UNKNOWN', error: 'Invalid characters in room alias' },
  httpStatus: 400                                          
}                                                          
```

**Bridge version**
Docker image at tag `release-1.8.0`

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Element
 - Version: 1.7.28
 But that's not very useful in this case...

**Additional context**
N/A

**Comment by Half-Shot** [comment]
We need to improve the schema here to reject bad alias characters.
