### ISSUE TITLE
"Can't join remote room because no servers that are in the room have been provided."

### ISSUE THREAD

**Issue by jkms** [matrix-org/matrix-appservice-slack#730]
So, basically I had all of this working correctly.  The problem was that I used the compiled `npm` version.  After I got it working, I decided to migrate to `docker` in order to daemonize everything.  Now it doesn't work.  The error is "Can't join remote room because no servers that are in the room have been provided."

I am using the following `docker` command to generate my slack-registration:
```
docker run -v /opt/matrix-appservice-slack/config/:/config/ matrixdotorg/matrix-appservice-slack -r -c /config/config.yaml -u "http://localhost:1313" -f /config/slack-registration.yaml
```
and the following command to run the service:
```
docker run -d --name matrix-appservice-slack --restart unless-stopped --network="host" -v /opt/matrix-appservice-slack/config/:/config/ matrixdotorg/matrix-appservice-slack
```

but the slackbot never accepts the room invite:
![image](https://user-images.githubusercontent.com/660916/214507860-7752afd4-5c78-43bd-82b4-f8ad007a3ef9.png)

## Docker Logs

```
INFO 07:22:22:757 [Main] Enabled RTM
INFO 07:22:22:761 [Main] Enabled hook handler
INFO 07:22:22:775 [Main] Loading databases
INFO 07:22:22:945 [PgDatastore] Database schema is at version v15
INFO 07:22:22:954 [SlackHookHandler] Slack-side listening on port 9898 over http
ERROR 07:22:23:003 [MatrixHttpClient] (REQ-2) {
  errcode: 'M_UNKNOWN',
  error: "Can't join remote room because no servers that are in the room have been provided."
}
ERROR 07:22:23:005 [Main] Homeserver cannot reach the bridge. You probably need to adjust your configuration. Error: Failed to join room
    at Intent._ensureJoined (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/intent.js:805:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Intent.sendEvent (/usr/src/app/node_modules/matrix-appservice-bridge/lib/components/intent.js:281:9)
    at async Bridge.pingAppserviceRoute (/usr/src/app/node_modules/matrix-appservice-bridge/lib/bridge.js:1100:9)
    at async Main.pingBridge (/usr/src/app/lib/Main.js:1494:26)
    at async Main.run (/usr/src/app/lib/Main.js:995:9)
INFO 07:22:23:014 [Main] Ensuring the bridge bot is registered
WARN 07:22:23:035 [Main] The bot is not in the admin room. You should invite the bot in order to control the bridge.
INFO 07:22:23:036 [Main] Fetching teams
INFO 07:22:23:039 [Main] Loaded 0 teams
INFO 07:22:23:044 [Main] Finished loading all team clients
INFO 07:22:23:048 [Main] Found 0 room entries in store
INFO 07:22:23:055 [Main] Bridge initialised
INFO 07:22:23:056 [app] Matrix-side listening on port 5858
```

## error.log.2023-01-25
```
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 34324\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 9924\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 23720\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 36708\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 12412\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
```

## debug.log.2023-01-25
```
{"data":["Enabled RTM"],"level":"info","module":"Main"}
{"data":["Enabled hook handler"],"level":"info","module":"Main"}
{"data":["Loading databases"],"level":"info","module":"Main"}
{"data":["Database schema is at version v15"],"level":"info","module":"PgDatastore"}
{"data":["Slack-side listening on port 9898 over http"],"level":"info","module":"SlackHookHandler"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["Ensuring the bridge bot is registered"],"level":"info","module":"Main"}
{"data":["The bot is not in the admin room. You should invite the bot in order to control the bridge."],"level":"warn","module":"Main"}
{"data":["Fetching teams"],"level":"info","module":"Main"}
{"data":["Loaded 0 teams"],"level":"info","module":"Main"}
{"data":["Finished loading all team clients"],"level":"info","module":"Main"}
{"data":["Found 0 room entries in store"],"level":"info","module":"Main"}
{"data":["Bridge initialised"],"level":"info","module":"Main"}
{"data":["Matrix-side listening on port",5858],"level":"info","module":"app"}
{"data":["Enabled RTM"],"level":"info","module":"Main"}
{"data":["Enabled hook handler"],"level":"info","module":"Main"}
{"data":["Loading databases"],"level":"info","module":"Main"}
{"data":["Database schema is at version v15"],"level":"info","module":"PgDatastore"}
{"data":["Slack-side listening on port 9898 over http"],"level":"info","module":"SlackHookHandler"}
{"data":["(REQ-2) {\n  errcode: 'M_LIMIT_EXCEEDED',\n  error: 'Too Many Requests',\n  retry_after_ms: 12412\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["Ensuring the bridge bot is registered"],"level":"info","module":"Main"}
{"data":["The bot is not in the admin room. You should invite the bot in order to control the bridge."],"level":"warn","module":"Main"}
{"data":["Fetching teams"],"level":"info","module":"Main"}
{"data":["Loaded 0 teams"],"level":"info","module":"Main"}
{"data":["Finished loading all team clients"],"level":"info","module":"Main"}
{"data":["Found 0 room entries in store"],"level":"info","module":"Main"}
{"data":["Bridge initialised"],"level":"info","module":"Main"}
{"data":["Matrix-side listening on port",5858],"level":"info","module":"app"}
{"data":["Enabled RTM"],"level":"info","module":"Main"}
{"data":["Enabled hook handler"],"level":"info","module":"Main"}
{"data":["Loading databases"],"level":"info","module":"Main"}
{"data":["Database schema is at version v15"],"level":"info","module":"PgDatastore"}
{"data":["Slack-side listening on port 9898 over http"],"level":"info","module":"SlackHookHandler"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["Ensuring the bridge bot is registered"],"level":"info","module":"Main"}
{"data":["The bot is not in the admin room. You should invite the bot in order to control the bridge."],"level":"warn","module":"Main"}
{"data":["Fetching teams"],"level":"info","module":"Main"}
{"data":["Loaded 0 teams"],"level":"info","module":"Main"}
{"data":["Finished loading all team clients"],"level":"info","module":"Main"}
{"data":["Found 0 room entries in store"],"level":"info","module":"Main"}
{"data":["Bridge initialised"],"level":"info","module":"Main"}
{"data":["Matrix-side listening on port",5858],"level":"info","module":"app"}
{"data":["Enabled RTM"],"level":"info","module":"Main"}
{"data":["Enabled hook handler"],"level":"info","module":"Main"}
{"data":["Loading databases"],"level":"info","module":"Main"}
{"data":["Database schema is at version v15"],"level":"info","module":"PgDatastore"}
{"data":["Slack-side listening on port 9898 over http"],"level":"info","module":"SlackHookHandler"}
{"data":["(REQ-2) {\n  errcode: 'M_UNKNOWN',\n  error: \"Can't join remote room because no servers that are in the room have been provided.\"\n}"],"level":"error","module":"MatrixHttpClient"}
{"data":["Homeserver cannot reach the bridge. You probably need to adjust your configuration.",{}],"level":"error","module":"Main"}
{"data":["Ensuring the bridge bot is registered"],"level":"info","module":"Main"}
{"data":["The bot is not in the admin room. You should invite the bot in order to control the bridge."],"level":"warn","module":"Main"}
{"data":["Fetching teams"],"level":"info","module":"Main"}
{"data":["Loaded 0 teams"],"level":"info","module":"Main"}
{"data":["Finished loading all team clients"],"level":"info","module":"Main"}
{"data":["Found 0 room entries in store"],"level":"info","module":"Main"}
{"data":["Bridge initialised"],"level":"info","module":"Main"}
{"data":["Matrix-side listening on port",5858],"level":"info","module":"app"}
```

## /opt/matrix-appservice-slack/config/config.yaml
```
homeserver:
  # The domain name of your homeserver
  #
  server_name: myserver.com
  
  # The URL for connecting to your homeserver
  #
  url: http://localhost:8008
  
  # The public facing url for media on your homeserver.
  # This is usually the public url of your homeserver.
  # Optional. Defaults to the value of `url`.
  #
  media_url: "https://matrix.myserver.com"
  
  # Optional. The maximum size of a uploaded file to Matrix in bytes. No limit by default
  #
  #max_upload_size: 104857600
  
  # Optional. Used to specify the port of the appservice in the config, rather than the command line.
  # This will be overriden by any ports given in the process arguments.
  #
  #appservice_port: 5858

  # Optional. Used to specify the host to listen on for the appservice.
  # appservice_host: 0.0.0.0

# The prefix to give Slack users on the Matrix server
#
username_prefix: "slack_"

# Maximum number of monthly active users, beyond this the bridge is getting blocked
# rmau_limit: 100

# Settings for database connection
# Optional. Defaults engine to "nedb".
#
db:
  # Which database engine to use.
  # Recommended: "postgres"
  # Deprecated: "nedb"
  #
  engine: "postgres"
  
  # A postgres connection string (unused if using nedb)
  #
  connectionString: "postgresql://slackbridge_user:RedactedPassword@localhost/slack_bridge"

# Optional. Use a matrix room to issue link and unlink commands to the bridge
#
matrix_admin_room: "!gpAVfzHIYdYlZPpcdf:myserver.com"

# Optional. TLS files to be used when handling Slack requests
#tls:
  #key_file: /path/to/tls.key
  #crt_file: /path/to/tls.crt

# Real Time Messaging API (RTM)
# Optional if slack_hook_port and inbound_uri_prefix are defined, required otherwise.
#
rtm:
  # Use the RTM API to listen for requests, which does not require
  # the bridge to listen on the hook port.
  # You should leave this enabled, unless you plan to use the
  # bridge exclusively for webhooks.
  #
  enable: true

  # Logging level specific to RTM traffic.
  #
  log_level: "silent"

# Port for incoming Slack requests from webhooks and event API messages
# Optional if using RTM API, required otherwise.
#
slack_hook_port: 9898

# Prefix of incoming requests to strip. This is NOT the bind host.
# Unlike most of the other urls, this one cannot use localhost,
# as this one must be publicly visible to the Slack API.
# Optional if using RTM API, required otherwise.
#
#inbound_uri_prefix: "https://my.server.here:9898/"

# Optional. Allow users to add channels dynamically by using oauth, or puppet themselves.
#
#oauth2:
  #client_id: ""
  #client_secret: ""
  
  # A prefix similar to inbound_uri_prefix for oauth2 requests. inbound_uri_prefix will be used if this is not set
  # Optional
  #
  #redirect_prefix: "https://my.server.here:9898/mycustomoauthendpoint"

# Optional
logging:
  console: "info" # One of "debug", "info", "warning", "error", "silent"
  
#   # Files that the bridge may log into. The key is the minimum level to report.
#   #
  files:
      "./debug.log": "info"
      "./error.log": "error"

# Optional. Enable metrics reporting on http://0.0.0.0:bridgePort/metrics which can be scraped by prometheus
#
# enable_metrics: true

# Optional. Sync team users and channels
#
# team_sync:
  # Entry for a single team
  # T0123ABCDEF:
  #   channels:
  #     enabled: true
  #     # Allow or deny private channels from being synced. Defaults to true.
  #     #
  #     allow_private: true
  #    
  #    # Optional. 
  #    # Allow or deny public channels from being synced. Defaults to true.
  #    #
  #    allow_public: true
  #  
  #
  #     # Optional. blacklist for channel ids. Trumps the whitelist.
  #     #
  #     #blacklist: ['CVCCPEY9X', 'C0108F9K37X']
  #
  #     # Optional. whitelist for channel ids.
  #     #
  #     #whitelist: []
  #
  #     # Prefix for room aliases in Matrix
  #     #
  #     #alias_prefix: "slack_"
  #
  #     # Send a hint to channel admins how to invite matrix bridge if automatic join does not work
  #     #
  #     #hint_channel_admins: true
  #
  #   # Should sync *all* team users to Matrix
  #   #
  #   users:
  #     enabled: true
  # Defaults for all other teams
  # all:
  #   channels:
  #     enabled: false
  #     #whitelist: []
  #     #blacklist: []
  #     #alias_prefix: "slack_"
  #   users:
  #     enabled: false

# Optional.
#
# provisioning:
#   enabled: true

  # Should the bridge deny users bridging channels to private rooms.
  # Optional.
  # require_public_room: false
  
  # Should the bridge allow users to bridge private channels.
  # Optional. Defaults to true.
  # allow_private_channels: true
  # Limit the number of bridged rooms and teams.
  # Optional. Unlimited by default.
  # limits:
  #  room_count: 20
  #  team_count: 1
  
  # Allow deny list for which Slack channels may be bridged.
  # If allow is defined, all other channels are blocked by default
  # If deny is defined, all other channels are allowed by default
  # If both are defined, allow takes precedence.
  # Optional. 
  # channel_adl:
  #   allow: 
  #     #- "CCZ41UJV7"
  #     #- "#open.*"
  #   deny:
  #     #- "CRBCPA771"
  #     #- "#secret.*"

# Optional. Allows Matrix users to optionally authenticate their Slack accounts.
# When a Matrix user posts, the bridge will post using their Slack account.
#
# puppeting:
#   # Should the bridge allow users to puppet their accounts
#   #
#   enabled: false
  
  # Should the bridge send users a onboarding message when
  # they join a Slack channel for the first time.
  # Optional.
  # onboard_users: false
  
  # Settings regarding who can send direct messages.
  # If allow is defined, all other users are blocked by default
  # If deny is defined, all other users are allowed by default
  # If both are defined, allow takes precedence.
  # Optional.
  # direct_messages:
  #   allow:
  #     # Which Slack users may DM Matrix users.
  #     #
  #     slack: 
  #       #- "U0156TG3W48"
      
  #     # Which Matrix users may DM Slack users.
  #     #
  #     matrix: 
  #       #- "@badactor:badhost"
  #       #- "@.*:badhost"

  #   deny:
  #     # Which Slack users may NOT DM Matrix users.
  #     #
  #     slack: 
  #       #- "U0156TG3W48"
      
  #     # Which Matrix users may NOT DM Slack users.
  #     #
  #     matrix: 
  #       #- "@badactor:badhost"
  #       #- "@.*:badhost"

# # Optional. Set the bot's profile on startup
# bot_profile:
#   # Optional. Set the displayname.
#   #
#   displayname: "Slack Bridge"
  
#   # Optional. Set the avatar.
#   #
#   avatar_url: "mxc://half-shot.uk/ea64c71ee946ca2f61379abefe2c7d977d276fbb"

# # Optional. Enable encryption in DMs and private rooms.
# encryption:
#   # Should encryption be enabled
#   #
#   enabled: false

#   # The URL where the bridge can access pantalaimon
#   #
#   pantalaimon_url: "http://localhost:8004"

```

## /opt/matrix-appservice-slack/config/slack-registration.yaml
```
id: Redacted
hs_token: Redacted
as_token: Redacted
url: http://localhost:1313
sender_localpart: slackbot
namespaces:
  users:
    - exclusive: true
      regex: '@slack_.*:myserver.com'
```

## /etc/matrix-synapse/conf.d/server_name.yaml 
```
# This file is autogenerated, and will be recreated on upgrade if it is deleted.
# Any changes you make will be preserved.

# The domain name of the server, with optional explicit port.
# This is used by remote servers to connect to this server,
# e.g. matrix.org, localhost:8080, etc.
# This is also the last part of your UserID.
#
server_name: myserver.com
```

## /etc/matrix-synapse/conf.d/homeserver.yaml
```
...
# A list of application service config files to use
#
app_service_config_files:
  - "/opt/matrix-appservice-slack/config/slack-registration.yaml"
#  - app_service_1.yaml
#  - app_service_2.yaml
...
```

**Comment by jkms** [comment]
oh my god.

Despite the documentation saying to "Decide on a spare local TCP port" **and** having that work with the `npm` build, for some reason `docker` requires that the port _in fact_ be `5858`

![image](https://user-images.githubusercontent.com/660916/214510602-bb1c37a4-36e3-4f66-a7ea-27a939edd6c5.png)

recreating `slack-registration.yaml` with port `5858` instead of my randomly selected `1313` has solved the problem for me.

Might want to add some clarity to the documentation.

Regardless, thanks for bridge.  Now that it's working my life is just a little bit simpler.
