### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kneescars** [matrix-org/matrix-appservice-slack#784]
I have installed Synapse and it was working normally. I installed matrix-appservice-slack using thr Github code and I monitor what's going on with the containers via Portainer (I only monitor, everything I do is via CLI on Terminal).

After some bumps due to the awkward nature of my NAS, it worked as well. However, when I added `app_service_config_files` to homeserver.yaml, Synapse cannot see the slack-registration.yaml file by any means. 

The path is correct, i triple-checked to see if there was something wrong with typos or something like that, and nothing. I even validated the file according to [Synapse documentation](https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html), but the file is solid as well. I keep getting the error below. When the container runs, it spends some time starting,and after a while, it says "running", but  on Portainer, the dedicated Synapse port disappears from the containers list and the logs keep having the same mistake. This is the error I get from the logs:

`**********************************************************************************
 Error during initialisation:
     Traceback (most recent call last):
       File "/usr/local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 359, in setup
         hs.setup()
       File "/usr/local/lib/python3.11/site-packages/synapse/server.py", line 348, in setup
         self.datastores = Databases(self.DATASTORE_CLASS, self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/__init__.py", line 100, in __init__
         main = main_store_class(database, db_conn, hs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/__init__.py", line 170, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/events_bg_updates.py", line 107, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/experimental_features.py", line 40, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/devices.py", line 1700, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/devices.py", line 101, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/roommember.py", line 1549, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/room.py", line 2177, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/room.py", line 1712, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/room.py", line 154, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/registration.py", line 2327, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/profile.py", line 44, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/presence.py", line 85, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/presence.py", line 66, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/transactions.py", line 81, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/state.py", line 751, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/state.py", line 109, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/state.py", line 549, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_federation.py", line 2064, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/media_repository.py", line 199, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/media_repository.py", line 112, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/filtering.py", line 49, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_push_actions.py", line 1896, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/metrics.py", line 75, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_push_actions.py", line 263, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/end_to_end_keys.py", line 1449, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/e2e_room_keys.py", line 60, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/search.py", line 435, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/search.py", line 144, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/account_data.py", line 70, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/push_rule.py", line 137, in __init__
         super().__init__(database, db_conn, hs)
       File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/appservice.py", line 82, in __init__
         self.services_cache = load_appservices(
                               ^^^^^^^^^^^^^^^^^
       File "/usr/local/lib/python3.11/site-packages/synapse/config/appservice.py", line 76, in load_appservices
         with open(config_file) as f:
              ^^^^^^^^^^^^^^^^^
     FileNotFoundError: [Errno 2] No such file or directory: '/volume1/Docker/PortainerCE/synapse/data/slack-registration.yaml'
 
 There may be more information in the logs.
**********************************************************************************
I went through over and over to see if there was some gap, but the files seem to be correct, and if I take `app_service_config_files` off homeserrver.yaml file, Synapse runs smoothly (but then the Slack bridge cannot work).

Can someone give me a light here? Why isn't the container seeing this specific file, but is seeing homeserver.yaml normally? ANd why Synapse stops working when I add `app_service_config_files` to homeserver.yaml?

Thanks in advance.

**Comment by kneescars** [comment]
I don't know what was wrong, but it's related to my NAS OS, which is an Asustor. Trying to install via CLI led to several errors due to dependencies I could not control (sorry, I am a newbie). Ideally, if I could run the Docker app on the NAS, it would have been easier, but via Portainer, it worked. Now I have another issue, but I will open another ticket. Thanks.
